sudo: required
dist: precise
group: edge

language: android

cache:
    directories:
        - $HOME/.gradle/caches/$GRADLE_VERSION
        - $HOME/.gradle/caches/jars-1
        - $HOME/.gradle/native
        - $HOME/.gradle/wrapper
        - $HOME/.m2/repository/

before_cache:
    - rm -rf $HOME/.gradle/daemon/
    - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock

jdk: oraclejdk8

git:
    depth: 10

branches:
    only:
    - develop
    - master
    - /release-.*$/

matrix:
    fast_finish: true

env:
    matrix:
    - TEST_SUITE="build" MODULE_DIR="annotation"
    - TEST_SUITE="build" MODULE_DIR="core"
    - TEST_SUITE="build" MODULE_DIR="processor"
    - TEST_SUITE="build" MODULE_DIR="testapp"
    global:
    - MALLOC_ARENA_MAX=2
    - TERM=dumb
    - ADB_INSTALL_TIMEOUT=12
    - export GRADLE_VERSION=$(sed -n "/[0-9]\.[0-9]/p" gradle/wrapper/gradle-wrapper.properties | cut -c 67-69)

android:
  components:
     - platform-tools
     - tools
     - build-tools-25.0.2
     - android-25
     - extra-android-m2repository
     - extra-android-support

before_install:
    - bash "ci/run_before_install.sh"

script:
    - bash "ci/run_script.sh"

after_failure:
    - bash "ci/run_after_failure.sh"
